version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_MULTIPLE_DATABASES=product_service,inventory_service,order_service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - microservices-network

  product-service:
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "5104:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=product_service;Username=postgres;Password=mysecretpassword;Port=5432
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
    networks:
      - microservices-network

  inventory-service:
    build:
      context: .
      dockerfile: InventoryService.API/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
      - product-service
    ports:
      - "5105:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=inventory_service;Username=postgres;Password=mysecretpassword;Port=5432
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
      - Services__ProductService=http://product-service
    networks:
      - microservices-network

  order-service:
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
      - product-service
      - inventory-service
    ports:
      - "5106:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=order_service;Username=postgres;Password=mysecretpassword;Port=5432
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
      - Services__ProductService=http://product-service
      - Services__InventoryService=http://inventory-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres-data: